---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: NTP
            bgp_as: 1
            ntp_server_ip_list: "1.1.1.1, 2001:1:2::1, 2.2.2.2"
            ntp_server_vrf: "management, default, admin"