---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: tenant_dhcp
            bgp_as: 1
            enable_tenant_dhcp: True
