---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: VRF_LITE
            bgp_as: 1
            vrf_lite_autoconfig: 1
            auto_symmetric_vrf_lite: True
            auto_vrflite_ifc_default_vrf: True
            auto_symmetric_default_vrf: True
            default_vrf_redis_bgp_rmap: extcon-rmap-filter
