- name: test my new module
  hosts: localhost
  tasks:
  - name: run the new module
    my_test:
      name: 'this is a test of a very long name'
      new: false
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'

