---
-   hosts: ndfc
    gather_facts: false
    tasks:
        - cisco.dcnm.dcnm_easy_fabric:
            state: merged
            config:
            -   fabric_name: IR-Fabric
                advertise_pip_bgp: True
                anycast_bgw_advertise_pip: True
                anycast_gw_mac: 00:aa:bb:cc:dd:ee
                anycast_rp_ip_range: 10.65.0.0/16
                bgp_as: 65535.65535
                replication_mode: Ingress
                vrf_lite_autoconfig: 1
                auto_symmetric_vrf_lite: True
                auto_vrflite_ifc_default_vrf: True
                auto_symmetric_default_vrf: True
                default_vrf_redis_bgp_rmap: extcon-rmap-filter
            -   fabric_name: MC-Fabric
                anycast_gw_mac: 00ffeeddccbb
                advertise_pip_bgp: False
                anycast_bgw_advertise_pip: False
                bfd_enable: True
                bfd_auth_enable: True
                bfd_auth_key: "asadflkajsdff"
                bfd_auth_key_id: 100
                bgp_as: 65535.0
                vrf_lite_autoconfig: 1
            -   fabric_name: AS_Plain
                anycast_gw_mac: 00dd.ccbb.aa00
                bgp_as: 4294967295
                bgp_lb_id: 1023
                bgp_auth_enable: True
                bgp_auth_key: "asdfasdfasdf"
                bgp_auth_key_type: "3"
                pm_enable: True
            -   fabric_name: Bootstrap
                bgp_as: 1
                bootstrap_enable: True
                dhcp_end: 5.1.1.5
                dhcp_start: 5.1.1.2
                dhcp_enable: True
                # Unlike every other *_enable parameter,
                # dhcp_ipv6_enable is not a boolean.
                # It has only one valid value: DHCPv4
                # If this is not set, NDFC will default
                # to DHCPv4, but this behavior may change
                # in the future.
                # dhcp_ipv6_enable: DHCPv4
                mgmt_gw: 5.1.1.1
                mgmt_prefix: 24
                bootstrap_multisubnet: |
                    10.6.0.2, 10.6.0.9, 10.6.0.1, 24
                    # This is a comment
                    10.7.0.2, 10.7.0.9, 10.7.0.1, 24
                bootstrap_conf: |
                    interface Ethernet1/1
                      no shutdown