---
-   hosts: ndfc
    gather_facts: false
    tasks:
        - cisco.dcnm.dcnm_easy_fabric:
            state: merged
            config:
            -   fabric_name: IR-Fabric
                advertise_pip_bgp: True
                bgp_as: 65535.65535
                anycast_rp_ip_range: 10.65.0.0/16
                replication_mode: Ingress
            -   fabric_name: MC-Fabric
                bgp_as: 65535.0
            -   fabric_name: AS_Plain
                bgp_as: 4294967295
                pm_enable: True
