---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: DNS
            bgp_as: 1
            dns_server_ip_list: "1.1.1.1, 2001:1:2::1, 2.2.2.2"
            dns_server_vrf: "management, foo, bar"
