---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: MPLS
            bgp_as: 1
            mpls_handoff: True
            mpls_lb_id: 101
            mpls_loopback_ip_range: 10.101.0.0/25
