---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: STP_MST
            bgp_as: 1
            stp_root_option: mst
            stp_bridge_priority: 8192
            mst_instance_range: 0-3,5,7-9
