---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: PBR
            bgp_as: 1
            enable_pbr: True
            esr_option: ePBR
