-   hosts: ndfc
    gather_facts: false
    tasks:
    -   name: detach policies
        cisco.dcnm.dcnm_image_upgrade:
            state: deleted                      # Mandatory, one of: merged, deleted, query
            config:
                policy: OLDER                   # Policy name to which switches are attached
                                                # - mandatory if not specified in switches list
                switches:                       # Mandatory list of dict, per-switch override of the global config
                -   ip_address: 172.22.150.102
                -   ip_address: 172.22.150.103
                -   ip_address: 172.22.150.113
        register: result
    -   name: print result
        ansible.builtin.debug:
            var: result

