---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: STP_RPVST
            bgp_as: 1
            stp_root_option: rpvst+
            stp_bridge_priority: 4096
            stp_vlan_range: 1,10-11,13,15-16
