---
-   hosts: ndfc
    gather_facts: false
    tasks:
    - cisco.dcnm.dcnm_easy_fabric:
        state: merged
        config:
        -   fabric_name: Syslog
            bgp_as: 1
            syslog_server_ip_list: "1.1.1.1, 2001:1:2::1, 2.2.2.2"
            syslog_server_vrf: "management, default, admin"
            syslog_sev: "1, 4, 5"
